# Generated by Django 5.2.17 on 2026-09-16 13:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("demandes", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="modifié le"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("DEMANDE_ENVOYEE", "Demande envoyée"),
                            ("DEMANDE_RENVOYEE", "Demande renvoyée après compléments"),
                            ("RELANCE", "Relance"),
                            ("COMPLEMENTS_DEMANDES", "Compléments demandés"),
                            ("DEMANDE_TRAITEE", "Demande traitée"),
                        ],
                        max_length=40,
                        verbose_name="type",
                    ),
                ),
                ("titre", models.CharField(max_length=200, verbose_name="titre")),
                ("message", models.TextField(verbose_name="message")),
                (
                    "payload",
                    models.JSONField(blank=True, default=dict, verbose_name="données"),
                ),
                ("lu", models.BooleanField(default=False, verbose_name="lue")),
                (
                    "lu_le",
                    models.DateTimeField(blank=True, null=True, verbose_name="lue le"),
                ),
                (
                    "demande",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="demandes.demande",
                    ),
                ),
                (
                    "destinataire",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "notification",
                "verbose_name_plural": "notifications",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["destinataire", "lu", "-created_at"],
                        name="notificatio_destina_a5756e_idx",
                    )
                ],
            },
        ),
    ]
