# Generated by Django 5.2.17 on 2026-09-16 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[
                    ("DEMANDE_ENVOYEE", "Demande envoyée"),
                    ("DEMANDE_RENVOYEE", "Demande renvoyée après compléments"),
                    ("RELANCE", "Relance"),
                    ("COMPLEMENTS_DEMANDES", "Compléments demandés"),
                    ("DEMANDE_TRAITEE", "Demande traitée"),
                    ("PROJET_ATTESTATION_SOUMIS", "Projet d'attestation soumis"),
                    (
                        "PROJET_ATTESTATION_A_CORRIGER",
                        "Projet d'attestation à corriger",
                    ),
                    ("ATTESTATION_DISPONIBLE", "Attestation disponible"),
                ],
                max_length=40,
                verbose_name="type",
            ),
        ),
    ]
