# Generated by Django 5.2.17 on 2026-09-16 13:29

import apps.pieces.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("demandes", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TypePiece",
            fields=[
                (
                    "code",
                    models.CharField(
                        max_length=40,
                        primary_key=True,
                        serialize=False,
                        verbose_name="code",
                    ),
                ),
                ("libelle", models.CharField(max_length=200, verbose_name="libellé")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "ordre",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="ordre d'affichage"
                    ),
                ),
            ],
            options={
                "verbose_name": "type de pièce",
                "verbose_name_plural": "types de pièces",
                "ordering": ["ordre", "code"],
            },
        ),
        migrations.CreateModel(
            name="PieceJointe",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="modifié le"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "fichier",
                    models.FileField(
                        max_length=255,
                        upload_to=apps.pieces.models.chemin_piece,
                        verbose_name="fichier",
                    ),
                ),
                (
                    "nom_fichier",
                    models.CharField(max_length=255, verbose_name="nom de la pièce"),
                ),
                (
                    "nom_original",
                    models.CharField(max_length=255, verbose_name="nom d'origine"),
                ),
                ("mime", models.CharField(max_length=100, verbose_name="type MIME")),
                (
                    "taille",
                    models.PositiveBigIntegerField(verbose_name="taille (octets)"),
                ),
                (
                    "sha256",
                    models.CharField(
                        db_index=True, max_length=64, verbose_name="empreinte SHA-256"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="supprimée le"
                    ),
                ),
                (
                    "demande",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pieces",
                        to="demandes.demande",
                    ),
                ),
                (
                    "deposee_par",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "type_piece",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pieces",
                        to="pieces.typepiece",
                    ),
                ),
            ],
            options={
                "verbose_name": "pièce jointe",
                "verbose_name_plural": "pièces jointes",
                "ordering": ["created_at"],
            },
        ),
    ]
