# Generated by Django 5.2.17 on 2026-09-16 13:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("demandes", "0002_alter_historiquetransition_action"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Attestation",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="modifié le"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("PROJET", "Projet d'attestation (distributeur)"),
                            ("DEFINITIVE", "Attestation définitive (siège)"),
                        ],
                        max_length=20,
                        verbose_name="type",
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("EN_EDITION", "En cours d'édition"),
                            ("SOUMISE", "Soumise au siège"),
                            ("A_CORRIGER", "À corriger"),
                            ("VALIDEE", "Validée"),
                        ],
                        default="EN_EDITION",
                        max_length=20,
                        verbose_name="statut",
                    ),
                ),
                ("contenu_html", models.TextField(verbose_name="contenu HTML")),
                (
                    "contenu_json",
                    models.JSONField(
                        blank=True, null=True, verbose_name="document éditeur"
                    ),
                ),
                (
                    "variables_snapshot",
                    models.JSONField(default=dict, verbose_name="variables"),
                ),
                (
                    "numero",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="numéro d'attestation"
                    ),
                ),
                (
                    "pdf",
                    models.FileField(
                        blank=True,
                        max_length=255,
                        upload_to="attestations/%Y/%m/",
                        verbose_name="PDF",
                    ),
                ),
                (
                    "validated_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="validée le"
                    ),
                ),
                (
                    "justification_forcage",
                    models.TextField(
                        blank=True, verbose_name="justification du forçage"
                    ),
                ),
                (
                    "soumise_le",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="soumise au siège le"
                    ),
                ),
                (
                    "commentaire_siege",
                    models.TextField(
                        blank=True,
                        verbose_name="commentaire du siège (demande de correction)",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "demande",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attestations",
                        to="demandes.demande",
                    ),
                ),
                (
                    "validated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "attestation",
                "verbose_name_plural": "attestations",
                "ordering": ["kind"],
                "unique_together": {("demande", "kind")},
            },
        ),
        migrations.CreateModel(
            name="AnalyseIA",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="modifié le"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("COHERENT", "Cohérent"),
                            ("INCOHERENT", "Incohérences détectées"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "score",
                    models.PositiveSmallIntegerField(
                        verbose_name="score de cohérence (%)"
                    ),
                ),
                (
                    "contenu_hash",
                    models.CharField(
                        max_length=64, verbose_name="empreinte du contenu analysé"
                    ),
                ),
                ("resultat", models.JSONField(verbose_name="résultat détaillé")),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "attestation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analyses",
                        to="attestations.attestation",
                    ),
                ),
            ],
            options={
                "verbose_name": "analyse IA",
                "verbose_name_plural": "analyses IA",
                "ordering": ["-created_at"],
            },
        ),
    ]
