# Generated by Django 5.2.17 on 2026-09-16 13:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Demande",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="modifié le"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        editable=False,
                        max_length=20,
                        unique=True,
                        verbose_name="référence",
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("BROUILLON", "Brouillon"),
                            ("EN_COURS", "En cours d'instruction"),
                            ("A_COMPLETER", "Compléments demandés"),
                            ("TRAITE", "Traitée"),
                        ],
                        db_index=True,
                        default="BROUILLON",
                        max_length=20,
                        verbose_name="statut",
                    ),
                ),
                (
                    "decision",
                    models.CharField(
                        blank=True,
                        choices=[("ACCEPTEE", "Acceptée"), ("REFUSEE", "Refusée")],
                        db_index=True,
                        max_length=20,
                        null=True,
                        verbose_name="décision",
                    ),
                ),
                (
                    "commentaire_distributeur",
                    models.TextField(
                        blank=True, verbose_name="commentaire du distributeur"
                    ),
                ),
                (
                    "commentaire_siege",
                    models.TextField(blank=True, verbose_name="commentaire du siège"),
                ),
                (
                    "motif_refus",
                    models.TextField(blank=True, verbose_name="motif du refus"),
                ),
                (
                    "message_complements",
                    models.TextField(
                        blank=True, verbose_name="éléments complémentaires demandés"
                    ),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="dernier envoi au siège"
                    ),
                ),
                (
                    "first_submitted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="premier envoi au siège"
                    ),
                ),
                (
                    "nb_soumissions",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="nombre d'envois"
                    ),
                ),
                (
                    "decided_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="date de décision"
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(default=1, verbose_name="version"),
                ),
                (
                    "scoring_snapshot",
                    models.JSONField(
                        blank=True, null=True, verbose_name="scoring au dernier envoi"
                    ),
                ),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "distributeur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="demandes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="distributeur",
                    ),
                ),
            ],
            options={
                "verbose_name": "demande",
                "verbose_name_plural": "demandes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CompteurReference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prefixe", models.CharField(max_length=10)),
                ("annee", models.PositiveIntegerField()),
                ("valeur", models.PositiveIntegerField(default=0)),
            ],
            options={
                "unique_together": {("prefixe", "annee")},
            },
        ),
        migrations.CreateModel(
            name="HistoriqueTransition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="modifié le"),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATION", "Création"),
                            ("ENVOI", "Envoi au siège"),
                            ("RENVOI", "Renvoi après compléments"),
                            ("COMPLEMENTS", "Compléments demandés"),
                            ("ACCEPTATION", "Acceptation"),
                            ("REFUS", "Refus"),
                            ("RELANCE", "Relance"),
                        ],
                        max_length=40,
                        verbose_name="action",
                    ),
                ),
                (
                    "de_statut",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("BROUILLON", "Brouillon"),
                            ("EN_COURS", "En cours d'instruction"),
                            ("A_COMPLETER", "Compléments demandés"),
                            ("TRAITE", "Traitée"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "vers_statut",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("BROUILLON", "Brouillon"),
                            ("EN_COURS", "En cours d'instruction"),
                            ("A_COMPLETER", "Compléments demandés"),
                            ("TRAITE", "Traitée"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "decision",
                    models.CharField(
                        blank=True,
                        choices=[("ACCEPTEE", "Acceptée"), ("REFUSEE", "Refusée")],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("commentaire", models.TextField(blank=True)),
                (
                    "acteur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "demande",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historique",
                        to="demandes.demande",
                    ),
                ),
            ],
            options={
                "verbose_name": "événement d'historique",
                "verbose_name_plural": "historique",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="Relance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="modifié le"),
                ),
                ("message", models.TextField(blank=True, verbose_name="message")),
                (
                    "destinataires",
                    models.JSONField(default=list, verbose_name="destinataires"),
                ),
                (
                    "email_ok",
                    models.BooleanField(default=False, verbose_name="email envoyé"),
                ),
                (
                    "demande",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relances",
                        to="demandes.demande",
                    ),
                ),
                (
                    "envoyee_par",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "relance",
                "verbose_name_plural": "relances",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SoumissionFDR",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="modifié le"),
                ),
                (
                    "numero",
                    models.PositiveSmallIntegerField(verbose_name="numéro d'envoi"),
                ),
                (
                    "pdf",
                    models.FileField(
                        max_length=255,
                        upload_to="soumissions/%Y/%m/",
                        verbose_name="PDF du FDR",
                    ),
                ),
                ("fdr_snapshot", models.JSONField(verbose_name="FDR déclaré")),
                ("pieces_snapshot", models.JSONField(verbose_name="pièces jointes")),
                ("scoring_snapshot", models.JSONField(verbose_name="scoring")),
                ("commentaire_distributeur", models.TextField(blank=True)),
                (
                    "demande",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="soumissions",
                        to="demandes.demande",
                    ),
                ),
            ],
            options={
                "verbose_name": "soumission",
                "verbose_name_plural": "soumissions",
                "ordering": ["numero"],
            },
        ),
        migrations.CreateModel(
            name="FDR",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="modifié le"),
                ),
                (
                    "demande",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="fdr",
                        serialize=False,
                        to="demandes.demande",
                    ),
                ),
                (
                    "assure_nom",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="nom / raison sociale",
                    ),
                ),
                (
                    "assure_adresse",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="adresse de l'assuré",
                    ),
                ),
                (
                    "assure_code_postal",
                    models.CharField(
                        blank=True,
                        max_length=5,
                        null=True,
                        verbose_name="code postal de l'assuré",
                    ),
                ),
                (
                    "assure_ville",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="ville de l'assuré",
                    ),
                ),
                (
                    "assure_siret",
                    models.CharField(
                        blank=True,
                        max_length=14,
                        null=True,
                        verbose_name="SIRET de l'assuré",
                    ),
                ),
                (
                    "numero_contrat",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="numéro de contrat",
                    ),
                ),
                (
                    "reference_client",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        verbose_name="référence client",
                    ),
                ),
                (
                    "chantier_nom",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="nom du chantier",
                    ),
                ),
                (
                    "chantier_ville",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="ville du chantier",
                    ),
                ),
                (
                    "type_chantier",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("CONSTRUCTION_NEUVE", "Construction neuve"),
                            ("RENOVATION", "Rénovation"),
                        ],
                        max_length=30,
                        null=True,
                        verbose_name="type de chantier",
                    ),
                ),
                (
                    "modification_structure",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="modification de structure"
                    ),
                ),
                (
                    "usage",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("HABITATION", "Habitation"),
                            ("BUREAU", "Bureau"),
                            ("COMMERCE", "Commerce"),
                            ("AUTRE", "Autre"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="usage",
                    ),
                ),
                (
                    "usage_autre_precision",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="précision de l'usage",
                    ),
                ),
                (
                    "chantier_atypique",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="chantier atypique"
                    ),
                ),
                (
                    "date_debut",
                    models.DateField(
                        blank=True, null=True, verbose_name="date de début"
                    ),
                ),
                (
                    "date_fin",
                    models.DateField(blank=True, null=True, verbose_name="date de fin"),
                ),
                (
                    "cout_total",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=14,
                        null=True,
                        verbose_name="coût total (€)",
                    ),
                ),
                (
                    "description_travaux",
                    models.TextField(
                        blank=True, null=True, verbose_name="description des travaux"
                    ),
                ),
                (
                    "montant_prestation",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=14,
                        null=True,
                        verbose_name="montant de la prestation (€)",
                    ),
                ),
                (
                    "type_intervention",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ENTREPRISE_PRINCIPALE", "Entreprise principale"),
                            ("SOUS_TRAITANT", "Sous-traitant"),
                        ],
                        max_length=30,
                        null=True,
                        verbose_name="type d'intervention",
                    ),
                ),
                (
                    "entreprise_principale_nom",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="entreprise principale",
                    ),
                ),
                (
                    "activite_couverte",
                    models.BooleanField(
                        blank=True,
                        null=True,
                        verbose_name="activité couverte par le contrat",
                    ),
                ),
                (
                    "activite_non_couverte_precision",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="précision sur l'activité non couverte",
                    ),
                ),
                (
                    "travaux_standards",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="travaux standards"
                    ),
                ),
            ],
            options={
                "verbose_name": "FDR",
                "verbose_name_plural": "FDR",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("date_fin__isnull", True),
                            ("date_debut__isnull", True),
                            ("date_fin__gte", models.F("date_debut")),
                            _connector="OR",
                        ),
                        name="fdr_date_fin_apres_debut",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("cout_total__isnull", True),
                            ("cout_total__gt", 0),
                            _connector="OR",
                        ),
                        name="fdr_cout_total_positif",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("montant_prestation__isnull", True),
                            ("montant_prestation__gt", 0),
                            _connector="OR",
                        ),
                        name="fdr_montant_prestation_positif",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="demande",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("decision__isnull", True), ("statut", "TRAITE"), _connector="OR"
                ),
                name="decision_uniquement_si_traitee",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="soumissionfdr",
            unique_together={("demande", "numero")},
        ),
    ]
