# Generated by Django 5.2.17 on 2026-09-16 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("demandes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historiquetransition",
            name="action",
            field=models.CharField(
                choices=[
                    ("CREATION", "Création"),
                    ("ENVOI", "Envoi au siège"),
                    ("RENVOI", "Renvoi après compléments"),
                    ("COMPLEMENTS", "Compléments demandés"),
                    ("ACCEPTATION", "Acceptation"),
                    ("REFUS", "Refus"),
                    ("RELANCE", "Relance"),
                    (
                        "ATTESTATION_PROJET_VALIDEE",
                        "Projet d'attestation validé (ancien circuit)",
                    ),
                    (
                        "ATTESTATION_PROJET_SOUMISE",
                        "Projet d'attestation soumis au siège",
                    ),
                    (
                        "ATTESTATION_PROJET_A_CORRIGER",
                        "Projet d'attestation renvoyé pour correction",
                    ),
                    (
                        "ATTESTATION_PROJET_ROUVERTE",
                        "Projet d'attestation repris par le distributeur",
                    ),
                    (
                        "ATTESTATION_DEFINITIVE_VALIDEE",
                        "Attestation définitive validée",
                    ),
                ],
                max_length=40,
                verbose_name="action",
            ),
        ),
    ]
